export const data = [
    {
        question: "Who made the famous painting 'Starry Night'",
        option1: "Vincent Van Gogh",
        option2: "Francisco Goya",
        option3: "Claude Monet",
        option4: "Frida Kahlo",
        ans: 1,
        image: "https://source.unsplash.com/",
    },
    {
        question: "What art movement is associated with Andy Warhol?",
        option1: "Cubism",
        option2: "Conceptualism",
        option3: "Surrrealism",
        option4: "Pop Art",
        ans: 4,
        image: "",
    },
    {
        question: "Where is The Louvre Museum located",
        option1: "Cairo,Egypts",
        option2: "Paris, France",
        option3: "Cape Town, South Africa",
        option4: "Amsterdam. Netherlands",
        ans: 2,   
        image: "https://source.unsplash.com/-F-C5EeYa-s",
    },
    {
        question: "Which French painter is most associated with paintings of water lilies",
        option1: "Claude Monet",
        option2: "Leonardp Da Vinci ",
        option3: "Salvador Dali",
        option4: "Pablo Picasso",
        ans: 1,
        image: "",
    },
    {
        question: "Who painted the 'Mona Lisa?'",
        option1: "Henri Matisse",
        option2: "Jackson Pollock",
        option3: "Leonardo Da Vinci",
        option4: "Edward Hopper",
        ans: 3,
        image: "",
    },
]