export const dataMusic = [
    {
        question: "Which composer learnt to play piano before he could read?",
        option1: "Erik Satie",
        option2: "Bach",
        option3: "Jimi Hendrix",
        option4: "Mozart",
        ans: 4,
        image: "",
    },
    {
        question: "What was Freddie Mercury's real name?",
        option1: "Paul McCarthney",
        option2: "Farrokh Bulsara",
        option3: "Barry White",
        option4: "John Lennon",
        ans: 2,
        image: "",
    },
    {
        question: "How does sound travel through air?",
        option1: "Vibrations",
        option2: "Echo",
        option3: "Movement",
        option4: "Sound waves",
        ans: 1,   
        image: "",
    },
    {
        question: "What comes next: Do Re Mi Fa So _ _ _",
        option1: "El Ti Do",
        option2: "Mi La So",
        option3: "La Ti Do",
        option4: "Do Fa So",
        ans: 3,
        image: "",
    },
    {
        question: "Which classical composer was deaf?",
        option1: "Antonio Vivaldi",
        option2: "Ludwig van Beethoven",
        option3: "Igor Stravinsky",
        option4: "Marianna Martines",
        ans: 2,
        image: "",
    },
];