export const dataHistory = [
    {
        question: "Who was the first person in the world to walk on the moon?",
        option1: "Buzz Aldrin",
        option2: "Neil Armstrong",
        option3: "Alan Shepard",
        option4: "James Irwin",
        ans: 2,
        image: "",
    },
    {
        question: "Who won four gold medals in the 1936 Olympics, infuriating Adolf Hitler?",
        option1: "Ralph Metcalfe",
        option2: "Naoto Tajima",
        option3: "Carl Ludwig Luz Long",
        option4: "Jessie Owens",
        ans: 4,
        image: "",
    },
    {
        question: "Who invented the telephone?",
        option1: "Alexander Graham Bell",
        option2: "Thomas Edison",
        option3: "Nikola Tesla",
        option4: "Madam C.J. Walker",
        ans: 1,   
        image: "",
    },
    {
        question: "In what year was Nelson Mandela released from prison?",
        option1: "1994",
        option2: "1976",
        option3: "1990",
        option4: "1996",
        ans: 3,
        image: "",
    },
    {
        question: "Where did King Tutankhamun rule from 1332- 1323 B.C.?",
        option1: "Ethopia",
        option2: "Egypt",
        option3: "Mali",
        option4: "Morocco",
        ans: 2,
        image: "",
    },
];